query randomImageQuery(
  $source: SourceTypes!
  $query: String!
  $category:  CategoryTypes!
) {
  randomImage(source: $source, query: $query, category: $category) {
    id
    altDescription
    color
    description
    links {
      download
    }
    urls {
      full
      thumb
    }
    user {
      firstName
      lastName
      username
      links {
        html
      }
    }
    exif {
      make
      model
      exposureTime
      aperture
      focalLength
      iso
    }
    location {
      city
      country
      name
    }
  }
}
